version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: written-me
    environment:
      MYSQL_DATABASE: written_me
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    restart: always
    image: redis:alpine
    container_name: written_me_redis_container
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6381:6379"


volumes:
  mysql_data: