spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

openai:
  model: "gpt-3.5-turbo"
  api:
    key: ${OPEN_API_KEY}
    url: "https://api.openai.com/v1/chat/completions"

aws:
  s3:
    bucket: ${AWS_BUCKET}
  credentials:
    access-key: ${ACCESS_KEY}
    secret-key: ${SECRET_KEY}
  stack:
    auto: false
  region:
    static: ap-northeast-2