spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/migration_kotlin
    username: user
    password:

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

openai:
  model: "gpt-3.5-turbo"
  api:
    key: ${OPEN_API_KEY}
    url: "https://api.openai.com/v1/chat/completions"

file:
  dir: ${absolute_dir}